### ISSUE TITLE
d_a_obj_mknjd

### ISSUE THREAD

**Issue by magcius** [zeldaret/tww#422]
MknjD

**Comment by Sage-of-Mirrors** [comment]
In progress at https://github.com/Sage-of-Mirrors/tww/blob/obj_mknjd/src/d/actor/d_a_obj_mknjd.cpp

**Comment by Sage-of-Mirrors** [comment]
Major progress merged with PR #504. As of this PR:
* `daObjMknjD::Act_c::CreateHeap()` is at 95% with regswaps; all other functions match 100%.
* Structure of the TU needs to be adjusted to get the TU to match 100%.
